import React, { useState, useEffect } from 'react';
import {
    MessageCircle, Send, Users, Package, Bell, Zap, CheckCircle,
    Star, Phone, Sparkles, BarChart3, FileText, Tag, Clock, X, Plus
} from 'lucide-react';
import api from '../api/axios';

const COMPANY = {
    name:  'UNITY ELECTRONICS',
    phone: '+91 96993 74346',
    owner: 'Samarth Rajendra Shinde',
};

// ── Quick message templates ────────────────────────────────────────────────────
const TEMPLATES = {
    'Invoice Share': (customer, invoiceNo, total) =>
        `🧾 *Invoice from UNITY ELECTRONICS*\n\nDear *${customer}*,\n\nThank you for your purchase!\n\n📋 Invoice: *${invoiceNo}*\n💰 Amount Paid: *₹${Number(total).toLocaleString()}*\n\n✅ Payment received successfully.\n\nFor any queries:\n📞 ${COMPANY.phone}\n\n_Unity Electronics, Ishwarpur, Sangli_`,

    'Service Update': (customer, serviceNo, status, tech) =>
        `🔧 *Service Update — UNITY ELECTRONICS*\n\nDear *${customer}*,\n\nYour service request *#${serviceNo}* has been updated:\n\n📌 Status: *${status}*\n👨‍🔧 Technician: *${tech}*\n\nWe'll notify you upon completion.\n\n📞 ${COMPANY.phone}`,

    'Offer Broadcast': (festivalName, discount, items, validity) =>
        `${festivalName === 'Diwali' ? '🪔' : festivalName === 'Ganesh Chaturthi' ? '🐘' : '🎉'} *${festivalName.toUpperCase()} SPECIAL SALE*\n*UNITY ELECTRONICS, Ishwarpur*\n━━━━━━━━━━━━━━━━━━━━━━\n\n💥 *FLAT ${discount}% OFF* on:\n${items}\n\n📅 Valid till: ${validity}\n✅ Free Home Delivery\n✅ Easy EMI Available\n✅ Exchange Offers\n\n📞 *${COMPANY.phone}*\n📍 Ishwarpur, Tal. Walwa, Sangli\n\n_Hurry — Limited stock!_`,

    'AMC Reminder': (customer, appliance, contractNo, days, endDate) =>
        `🔔 *AMC Renewal Reminder*\n*UNITY ELECTRONICS*\n\nDear *${customer}*,\n\nYour *${appliance} AMC* (${contractNo}) expires in *${days} days* on ${endDate}.\n\n🛠 Renew now for uninterrupted service coverage!\n\n📞 ${COMPANY.phone}\n_Unity Electronics, Sangli_`,

    'Low Stock Alert': (ownerName, items) =>
        `⚠️ *LOW STOCK ALERT*\n_Unity ERP — Internal Report_\n\nDear ${ownerName},\n\nThe following items need urgent reorder:\n${items}\n\n📲 Login to Unity ERP to place orders.\n\n_Auto-generated by Unity ERP System_`,
};

const WhatsAppHub = () => {
    const [customers, setCustomers]         = useState([]);
    const [products, setProducts]           = useState([]);
    const [sales, setSales]                 = useState([]);
    const [activeTab, setActiveTab]         = useState('broadcast');
    const [logs, setLogs]                   = useState(() => { try { return JSON.parse(localStorage.getItem('unity_wa_logs') || '[]'); } catch { return []; } });
    const [broadcastForm, setBroadcastForm] = useState({ template: 'Offer Broadcast', festival: 'Diwali', discount: '20', items: 'AC, Refrigerator, LED TV, Washing Machine', validity: '' });
    const [serviceForm, setServiceForm]     = useState({ customer: '', serviceNo: '', status: 'Under Repair', tech: '' });
    const [invoiceForm, setInvoiceForm]     = useState({ saleId: '', customer: '' });
    const [customMsg, setCustomMsg]         = useState({ phone: '', message: '' });

    useEffect(() => {
        Promise.all([api.get('/customers'), api.get('/products'), api.get('/sales')])
            .then(([c, p, s]) => { setCustomers(c.data || []); setProducts(p.data || []); setSales(s.data || []); })
            .catch(() => {});
    }, []);

    const [sending, setSending] = useState(false);

    const addLog = (type, recipient, snippet) => {
        const entry = { id: Date.now(), type, recipient, snippet: snippet.slice(0, 60) + '…', sentAt: new Date().toISOString() };
        const newLogs = [entry, ...logs].slice(0, 50);
        setLogs(newLogs);
        localStorage.setItem('unity_wa_logs', JSON.stringify(newLogs));
    };

    const openWA = async (phone, message, logType, logRecipient) => {
        setSending(true);
        try {
            const clean = (phone || '').replace(/\D/g, '');
            await api.post('/whatsapp/send', { phone: clean, message, type: logType });
            addLog(logType, logRecipient, message);
            alert(`✅ Message securely sent via WhatsApp API to ${logRecipient}`);
        } catch (e) {
            alert('❌ Failed to send via API: ' + (e.response?.data?.message || e.message));
        } finally {
            setSending(false);
        }
    };

    // Broadcast to all customers via API
    const sendBroadcast = async () => {
        if (customers.length === 0) { alert('No customers found'); return; }
        const msg = TEMPLATES['Offer Broadcast'](broadcastForm.festival, broadcastForm.discount, broadcastForm.items.split(',').map(i => `  • ${i.trim()}`).join('\n'), broadcastForm.validity || 'Limited Period');
        
        setSending(true);
        const targets = customers.slice(0, 5); // Limit demo to 5
        let sentCount = 0;
        
        for (const c of targets) {
            try {
                const clean = (c.phone || '').replace(/\D/g, '');
                if (clean) {
                    await api.post('/whatsapp/send', { phone: clean, message: msg, type: 'Broadcast' });
                    sentCount++;
                }
            } catch (e) {}
        }
        
        addLog('Broadcast', `${sentCount} customers`, msg);
        setSending(false);
        alert(`✅ Broadcast successfully delivered to ${sentCount} customers via Official WhatsApp API!`);
    };

    const sendServiceUpdate = () => {
        const cust = customers.find(c => c.id == serviceForm.customer);
        if (!cust) return alert('Select a customer');
        const msg = TEMPLATES['Service Update'](cust.name, serviceForm.serviceNo, serviceForm.status, serviceForm.tech);
        openWA(cust.phone, msg, 'Service Update', cust.name);
    };

    const sendInvoice = () => {
        const sale = sales.find(s => s.id == invoiceForm.saleId);
        const cust = customers.find(c => c.id == (sale?.customer_id || invoiceForm.customer));
        if (!sale || !cust) return alert('Select a valid sale');
        const msg = TEMPLATES['Invoice Share'](cust.name, sale.invoice_number, sale.total_amount);
        openWA(cust.phone, msg, 'Invoice', cust.name);
    };

    const sendCustom = () => {
        if (!customMsg.phone || !customMsg.message) return alert('Enter phone & message');
        openWA(customMsg.phone, customMsg.message, 'Custom', customMsg.phone);
    };

    const sendLowStockAlert = () => {
        const lowItems = products.filter(p => p.stock_quantity < 10).map(p => `  • ${p.product_name} — ${p.stock_quantity} left`).join('\n');
        if (!lowItems) return alert('All stock levels are healthy!');
        const msg = TEMPLATES['Low Stock Alert'](COMPANY.owner, lowItems);
        openWA('9699374346', msg, 'Internal Alert', 'Owner');
    };

    const tabs = [
        { id: 'broadcast', label: '📢 Offer Broadcast', icon: Zap },
        { id: 'invoice',   label: '🧾 Send Invoice',    icon: FileText },
        { id: 'service',   label: '🔧 Service Update',  icon: Bell },
        { id: 'custom',    label: '✉️ Custom Message',  icon: MessageCircle },
        { id: 'logs',      label: `📋 Sent Logs (${logs.length})`, icon: BarChart3 },
    ];

    return (
        <div className="space-y-8 pb-10">
            {/* Header */}
            <div>
                <div className="flex items-center gap-3 mb-2">
                    <div className="h-12 w-12 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center">
                        <MessageCircle className="text-emerald-400" size={24} />
                    </div>
                    <div>
                        <h1 className="text-4xl font-black tracking-tighter">WhatsApp <span className="gradient-text">Integration</span></h1>
                        <p className="text-[11px] font-black uppercase tracking-[0.3em] text-slate-500">Auto Invoice · Offer Broadcast · Service Updates</p>
                    </div>
                </div>
            </div>

            {/* Quick Action Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {[
                    { label: 'Total Customers', value: customers.length, color: 'text-blue-400', icon: Users },
                    { label: 'Total Sales', value: sales.length, color: 'text-emerald-400', icon: FileText },
                    { label: 'Low Stock Items', value: products.filter(p => p.stock_quantity < 10).length, color: 'text-rose-400', icon: Package },
                    { label: 'Messages Sent', value: logs.length, color: 'text-purple-400', icon: Send },
                ].map(s => (
                    <div key={s.label} className="premium-card p-5 flex items-center gap-4">
                        <div className="h-12 w-12 rounded-2xl bg-white/5 flex items-center justify-center">
                            <s.icon className={s.color} size={22} />
                        </div>
                        <div>
                            <p className={`text-2xl font-black ${s.color}`}>{s.value}</p>
                            <p className="text-[9px] text-slate-500 font-black uppercase tracking-widest">{s.label}</p>
                        </div>
                    </div>
                ))}
            </div>

            {/* Quick Alert Row */}
            <div className="flex gap-3 flex-wrap">
                <button onClick={sendLowStockAlert}
                    className="flex items-center gap-2 px-5 py-3 bg-rose-500/10 text-rose-400 border border-rose-500/20 rounded-2xl font-black text-xs hover:bg-rose-500/20 transition-all">
                    <Bell size={15} /> Send Low Stock Alert to Owner
                </button>
                <div className="px-5 py-3 bg-emerald-500/10 border border-emerald-500/20 rounded-2xl font-black text-xs text-emerald-400 flex items-center gap-2">
                    <CheckCircle size={15} /> WhatsApp Web Ready — No API Key Needed
                </div>
            </div>

            {/* Tabs */}
            <div className="flex gap-2 flex-wrap">
                {tabs.map(tab => (
                    <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                        className={`px-5 py-2.5 rounded-2xl text-sm font-black transition-all ${activeTab === tab.id ? 'bg-primary text-white shadow-lg shadow-primary/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}>
                        {tab.label}
                    </button>
                ))}
            </div>

            {/* ─── Broadcast Tab ──────────────────────────────────────────────── */}
            {activeTab === 'broadcast' && (
                <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
                    <div className="premium-card space-y-5">
                        <h2 className="font-black text-lg flex items-center gap-2"><Zap className="text-yellow-400" size={20}/> Festival Offer Broadcast</h2>
                        <div>
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">Festival Name</label>
                            <input value={broadcastForm.festival} onChange={e => setBroadcastForm(p => ({ ...p, festival: e.target.value }))}
                                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm font-bold outline-none focus:border-primary text-foreground" />
                        </div>
                        <div>
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">Discount %</label>
                            <input type="number" value={broadcastForm.discount} onChange={e => setBroadcastForm(p => ({ ...p, discount: e.target.value }))}
                                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm font-bold outline-none focus:border-primary text-foreground" />
                        </div>
                        <div>
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">Products on Offer (comma-separated)</label>
                            <textarea value={broadcastForm.items} onChange={e => setBroadcastForm(p => ({ ...p, items: e.target.value }))} rows={3}
                                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm font-bold outline-none focus:border-primary text-foreground resize-none" />
                        </div>
                        <div>
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">Validity Date</label>
                            <input type="date" value={broadcastForm.validity} onChange={e => setBroadcastForm(p => ({ ...p, validity: e.target.value }))}
                                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm font-bold outline-none focus:border-primary text-foreground" />
                        </div>
                        <button onClick={sendBroadcast}
                            className="w-full py-4 bg-emerald-600 hover:bg-emerald-700 text-white rounded-2xl font-black text-sm flex items-center justify-center gap-2 transition-all shadow-lg shadow-emerald-600/20">
                            <MessageCircle size={18} /> Broadcast to All Customers ({customers.length})
                        </button>
                        <p className="text-[10px] text-slate-600 font-bold">⚠ Opens individual WhatsApp tabs. Bulk message requires WhatsApp Business API.</p>
                    </div>

                    {/* Message Preview */}
                    <div className="premium-card bg-[#0f1a10] border-emerald-900/30">
                        <p className="text-[10px] font-black uppercase tracking-widest text-emerald-600 mb-4">Message Preview</p>
                        <div className="bg-[#1a2e1a] rounded-2xl p-5">
                            <div className="bg-[#dcf8c6] text-slate-900 rounded-2xl rounded-tl-none px-4 py-3 max-w-xs text-xs font-bold leading-relaxed whitespace-pre-line shadow-md">
                                {TEMPLATES['Offer Broadcast'](broadcastForm.festival || 'Festival', broadcastForm.discount || '20', broadcastForm.items || '...', broadcastForm.validity || 'Limited Period')}
                            </div>
                            <p className="text-right mt-2 text-[10px] text-emerald-700 font-bold">✓✓</p>
                        </div>
                    </div>
                </div>
            )}

            {/* ─── Invoice Tab ────────────────────────────────────────────────── */}
            {activeTab === 'invoice' && (
                <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
                    <div className="premium-card space-y-5">
                        <h2 className="font-black text-lg flex items-center gap-2"><FileText className="text-primary" size={20}/> Share Invoice on WhatsApp</h2>
                        <div>
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">Select Sale / Invoice</label>
                            <select value={invoiceForm.saleId} onChange={e => setInvoiceForm(p => ({ ...p, saleId: e.target.value }))}
                                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm font-bold outline-none focus:border-primary text-foreground">
                                <option value="">Choose Invoice…</option>
                                {sales.slice(0, 30).map(s => {
                                    const c = customers.find(cu => cu.id === s.customer_id);
                                    return <option key={s.id} value={s.id} className="bg-slate-900">#{s.invoice_number} — {c?.name || 'Customer'} — ₹{Number(s.total_amount).toLocaleString()}</option>;
                                })}
                            </select>
                        </div>
                        {invoiceForm.saleId && (() => {
                            const sale = sales.find(s => s.id == invoiceForm.saleId);
                            const cust = customers.find(c => c.id === sale?.customer_id);
                            return sale && (
                                <div className="p-4 bg-primary/5 rounded-2xl border border-primary/20">
                                    <p className="text-xs font-black text-primary">{cust?.name} — {cust?.phone}</p>
                                    <p className="text-[10px] text-slate-500 font-bold mt-1">Invoice: #{sale.invoice_number} · ₹{Number(sale.total_amount).toLocaleString()}</p>
                                </div>
                            );
                        })()}
                        <button onClick={sendInvoice}
                            className="w-full py-4 bg-emerald-600 hover:bg-emerald-700 text-white rounded-2xl font-black text-sm flex items-center justify-center gap-2 transition-all">
                            <MessageCircle size={18} /> Send Invoice via WhatsApp
                        </button>
                    </div>

                    <div className="premium-card bg-[#0f1a10] border-emerald-900/30">
                        <p className="text-[10px] font-black uppercase tracking-widest text-emerald-600 mb-4">Preview</p>
                        <div className="bg-[#1a2e1a] rounded-2xl p-5">
                            <div className="bg-[#dcf8c6] text-slate-900 rounded-2xl rounded-tl-none px-4 py-3 max-w-xs text-xs font-bold leading-relaxed whitespace-pre-line shadow-md">
                                {TEMPLATES['Invoice Share']('Customer Name', 'UE-2025-001', '25000')}
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* ─── Service Update Tab ─────────────────────────────────────────── */}
            {activeTab === 'service' && (
                <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
                    <div className="premium-card space-y-5">
                        <h2 className="font-black text-lg flex items-center gap-2"><Bell className="text-yellow-400" size={20}/> Service Ticket Update</h2>
                        <div>
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">Customer</label>
                            <select value={serviceForm.customer} onChange={e => setServiceForm(p => ({ ...p, customer: e.target.value }))}
                                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm font-bold outline-none focus:border-primary text-foreground">
                                <option value="">Select Customer…</option>
                                {customers.map(c => <option key={c.id} value={c.id} className="bg-slate-900">{c.name} — {c.phone}</option>)}
                            </select>
                        </div>
                        {[
                            { key: 'serviceNo', label: 'Service Ticket No', ph: 'e.g. SRV-001' },
                            { key: 'tech', label: 'Technician Name', ph: 'e.g. Raju Mane' },
                        ].map(f => (
                            <div key={f.key}>
                                <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">{f.label}</label>
                                <input value={serviceForm[f.key]} onChange={e => setServiceForm(p => ({ ...p, [f.key]: e.target.value }))} placeholder={f.ph}
                                    className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm font-bold outline-none focus:border-primary text-foreground" />
                            </div>
                        ))}
                        <div>
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">Status</label>
                            <select value={serviceForm.status} onChange={e => setServiceForm(p => ({ ...p, status: e.target.value }))}
                                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm font-bold outline-none focus:border-primary text-foreground">
                                {['Received', 'Diagnosing', 'Under Repair', 'Waiting for Parts', 'Repaired — Ready for Pickup', 'Completed & Delivered'].map(s => (
                                    <option key={s} className="bg-slate-900">{s}</option>
                                ))}
                            </select>
                        </div>
                        <button onClick={sendServiceUpdate}
                            className="w-full py-4 bg-emerald-600 hover:bg-emerald-700 text-white rounded-2xl font-black text-sm flex items-center justify-center gap-2 transition-all">
                            <Send size={18} /> Send Service Update
                        </button>
                    </div>

                    <div className="premium-card bg-[#0f1a10] border-emerald-900/30">
                        <p className="text-[10px] font-black uppercase tracking-widest text-emerald-600 mb-4">Preview</p>
                        <div className="bg-[#1a2e1a] rounded-2xl p-5">
                            <div className="bg-[#dcf8c6] text-slate-900 rounded-2xl rounded-tl-none px-4 py-3 max-w-xs text-xs font-bold leading-relaxed whitespace-pre-line shadow-md">
                                {TEMPLATES['Service Update'](serviceForm.customer ? (customers.find(c => c.id == serviceForm.customer)?.name || 'Customer') : 'Customer', serviceForm.serviceNo || 'SRV-001', serviceForm.status, serviceForm.tech || 'Technician')}
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* ─── Custom Message Tab ─────────────────────────────────────────── */}
            {activeTab === 'custom' && (
                <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
                    <div className="premium-card space-y-5">
                        <h2 className="font-black text-lg flex items-center gap-2"><MessageCircle className="text-primary" size={20}/> Custom WhatsApp Message</h2>
                        <div>
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">Phone Number</label>
                            <div className="flex gap-2">
                                <span className="flex items-center px-3 bg-white/5 rounded-xl border border-white/10 text-sm font-black text-slate-400">+91</span>
                                <input value={customMsg.phone} onChange={e => setCustomMsg(p => ({ ...p, phone: e.target.value }))} placeholder="9XXXXXXXXX"
                                    className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm font-bold outline-none focus:border-primary text-foreground" />
                            </div>
                        </div>
                        <div>
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-1 block">Message</label>
                            <textarea value={customMsg.message} onChange={e => setCustomMsg(p => ({ ...p, message: e.target.value }))} rows={7} placeholder="Type your message using *bold* and _italic_ for WhatsApp formatting..."
                                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm font-bold outline-none focus:border-primary text-foreground resize-none leading-relaxed" />
                        </div>
                        {/* Quick insert buttons */}
                        <div className="flex gap-2 flex-wrap">
                            {['unity_greeting', 'paid_confirm', 'service_complete'].map(k => (
                                <button key={k} onClick={() => {
                                    const snippets = {
                                        unity_greeting: `Namaste! 🙏 This is *${COMPANY.name}*, your trusted electronics partner.\n`,
                                        paid_confirm:   `✅ Your payment has been received. Thank you!\n`,
                                        service_complete: `🔧 Your appliance has been repaired and is ready for pickup!\n`,
                                    };
                                    setCustomMsg(p => ({ ...p, message: p.message + snippets[k] }));
                                }} className="text-[9px] px-3 py-1.5 bg-white/5 hover:bg-white/10 text-slate-400 rounded-full font-black transition-all">
                                    + {k.replace(/_/g,' ')}
                                </button>
                            ))}
                        </div>
                        <button onClick={sendCustom}
                            className="w-full py-4 bg-emerald-600 hover:bg-emerald-700 text-white rounded-2xl font-black text-sm flex items-center justify-center gap-2 transition-all">
                            <Send size={18} /> Open in WhatsApp
                        </button>
                    </div>

                    <div className="premium-card bg-[#0f1a10] border-emerald-900/30">
                        <p className="text-[10px] font-black uppercase tracking-widest text-emerald-600 mb-4">Preview</p>
                        <div className="bg-[#1a2e1a] rounded-2xl p-5 min-h-[200px]">
                            {customMsg.message ? (
                                <div className="bg-[#dcf8c6] text-slate-900 rounded-2xl rounded-tl-none px-4 py-3 max-w-xs text-xs font-bold leading-relaxed whitespace-pre-line shadow-md">
                                    {customMsg.message}
                                </div>
                            ) : (
                                <p className="text-emerald-900 text-xs font-bold opacity-50">Type a message to see the preview…</p>
                            )}
                        </div>
                    </div>
                </div>
            )}

            {/* ─── Logs Tab ───────────────────────────────────────────────────── */}
            {activeTab === 'logs' && (
                <div className="premium-card overflow-hidden p-0">
                    <div className="p-6 border-b border-white/5 flex items-center justify-between">
                        <h2 className="font-black text-lg">Message History</h2>
                        <button onClick={() => { setLogs([]); localStorage.removeItem('unity_wa_logs'); }}
                            className="text-xs text-rose-400 font-black hover:text-rose-300 transition-colors">Clear All</button>
                    </div>
                    <div className="divide-y divide-white/5">
                        {logs.length === 0 ? (
                            <div className="text-center py-16 text-slate-500">
                                <MessageCircle size={40} className="mx-auto mb-3 opacity-20" />
                                <p className="font-bold">No messages sent yet.</p>
                            </div>
                        ) : logs.map(log => (
                            <div key={log.id} className="p-5 hover:bg-white/5 flex items-center gap-4">
                                <div className="h-10 w-10 rounded-2xl bg-emerald-600/10 flex items-center justify-center flex-shrink-0">
                                    <MessageCircle className="text-emerald-400" size={18} />
                                </div>
                                <div className="flex-1">
                                    <div className="flex items-center gap-2 mb-0.5">
                                        <span className="text-[9px] bg-primary/10 text-primary px-2 py-0.5 rounded-full font-black">{log.type}</span>
                                        <span className="font-black text-sm">{log.recipient}</span>
                                    </div>
                                    <p className="text-[10px] text-slate-500 font-bold truncate">{log.snippet}</p>
                                </div>
                                <div className="text-right">
                                    <Clock size={12} className="text-slate-600 inline mb-0.5" />
                                    <p className="text-[10px] text-slate-600 font-bold">{new Date(log.sentAt).toLocaleString('en-IN')}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
};

export default WhatsAppHub;
